<?xml version="1.0"?>
<package format="3">
  <name>seeed_usb_can_analyzer_driver</name>
  <version>0.1.0</version>
  <description>ROS 2 driver for the Seeed Studio USB-CAN Analyzer</description>
  <maintainer email="maintainer@example.com">maintainer</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
